### ISSUE TITLE
Bug with creating new Device inside a Network

### ISSUE THREAD

**Issue by MrKangs** [OPEnSLab-OSU/Spool#25] opened 2020-08-14 20:02 UTC
**Describe the bug**
When you create a new device in an existing network, both old and new devices get deleted and unable to access those devices and data again. 

**Expected behavior**
Usually, it should have created a new device inside the network while having the old device information/data. 

**Hardware in Use**
None of the hardware was used for this issue. Mainly for the website. 

**To Reproduce**
1. Go to Spool.open-sensing.org
2. Go to Dashboard if you are logged in. If not, then log in to your account.  
3. Once you get into Dashboard, Register New Network if you don't have a network setup. Else, Click view a network.
4. Click Register New Device
5. Type any name and click Register
Then you will see an empty network. 

**Screenshots**
![image](https://user-images.githubusercontent.com/24395305/90287812-75d4db00-de2d-11ea-9003-61dd20e82ee9.png)

This one the network before adding a new device.

![image](https://user-images.githubusercontent.com/24395305/90287873-943ad680-de2d-11ea-81bb-1406784f5564.png)

This is after creating a new device into the network. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Education
 - Browser Chrome
 - Version Chrome:  84.0.4147.125, Windows 10: 20H2

**Additional context**
At the same time, I believe that it should return a device id so that the user can add that information into the config. However, that is also not working as well. 

**Note**
I hope this issue/bug fixes as soon as possible because this is important for the documentation for Loom and Spool.

**Comment by eliwinkelman** [comment] 2020-08-14 21:00
Thanks for making an issue for this Ken. This was caused by an issue with the new devices name being set to null, causing an issue when the frontend tries to list the devices. This should be fixed for new networks/devices now.

**Closed as completed** 2020-08-14 21:00 UTC
Labels: bug
